version: '3'

services:
  database:
    container_name: database
    image: database
    build:
      context: database
    env_file: config/variables.env
    volumes:
      - ./volumes/backups:/root/backups

  wikifarm-master:
    container_name: wikifarm-master
    image: wikifarm-master
    build:
      context: wikifarm
      dockerfile: Dockerfile-master
    env_file: config/variables.env
    environment:
      MEDIAWIKI_PORT: ${MW_PORT}
    ports:
      - "${MW_PORT}:80"
    volumes:
      - ./volumes/mediawiki/master/config:/var/www/wikifarm/config
      - ./volumes/mediawiki/master/extensions:/var/www/wikifarm/extensions
      - ./volumes/mediawiki/master/skins:/var/www/wikifarm/skins
      - ./volumes/instances:/var/www/wikifarm/instances
