version: '3'

services:
  database:
    container_name: database
    image: mariadb
    env_file: config/variables.env

  wikifarm-1.31:
    container_name: wikifarm-1.31
    image: wikifarm-1.31
    build:
      context: wikifarm
      dockerfile: Dockerfile-1.31
    env_file: config/variables.env
    ports:
      - "${MW_PORT}:80"
    volumes:
      - ./volumes/config/1.31:/var/www/wikifarm/config
      - ./volumes/extensions/1.31:/var/www/mediawiki/extensions
      - ./volumes/instances:/var/www/wikifarm/instances
