version: '3'

services:
  database:
    container_name: database
    image: database
    build:
      context: database
    env_file: config/variables.env
    volumes:
      - ./volumes/backups:/root/backups

  wikifarm-1.32:
    container_name: wikifarm-1.32
    image: wikifarm-1.32
    build:
      context: wikifarm
      dockerfile: Dockerfile-1.32
    env_file: config/variables.env
    environment:
      MEDIAWIKI_PORT: ${MW_PORT}
    ports:
      - "${MW_PORT}:80"
    volumes:
      - ./volumes/mediawiki/1.32/config:/var/www/wikifarm/config
      - ./volumes/mediawiki/1.32/extensions:/var/www/wikifarm/extensions
      - ./volumes/mediawiki/1.32/skins:/var/www/wikifarm/skins
      - ./volumes/instances:/var/www/wikifarm/instances
