version: '3'

services:
  database:
    container_name: database
    image: mariadb
    env_file: config/variables.env

  wikifarm-master:
    container_name: wikifarm-master
    image: wikifarm-master
    build:
      context: wikifarm
      dockerfile: Dockerfile-master
    env_file: config/variables.env
    ports:
      - "${MW_PORT}:80"
    volumes:
      - ./volumes/config:/var/www/wikifarm/config
      - ./volumes/instances:/var/www/wikifarm/instances
      - ./volumes/extensions:/var/www/mediawiki/extensions
