version: '3'

services:
  database:
    container_name: database
    image: database
    build:
      context: database
    env_file: config/variables.env
    volumes:
      - ./volumes/backups:/root/backups

  wikifarm-1.33:
    container_name: wikifarm-1.33
    image: wikifarm-1.33
    build:
      context: wikifarm
      dockerfile: Dockerfile-1.33
    env_file: config/variables.env
    environment:
      MEDIAWIKI_PORT: ${MW_PORT}
    ports:
      - "${MW_PORT}:80"
    volumes:
      - ./volumes/config/1.33:/var/www/wikifarm/config
      - ./volumes/extensions/1.33:/var/www/mediawiki/extensions
      - ./volumes/instances:/var/www/wikifarm/instances
