FROM php:7.3-apache

ENV MEDIAWIKI_BRANCH master

RUN set -eux; \
	rm /etc/apt/preferences.d/no-debian-php; \
	apt-get update; \
	apt-get install -y --no-install-recommends \
		composer \
		lua5.1 \
		lua5.1-dev \
		libxml2-dev \
		pkg-config \
		php-xml \
		php-dom \
		zip \
		unzip \
		make \
		; \
	docker-php-ext-install -j "$(nproc)" \
		dom \
		xml \
		; \
	pecl install \
		luasandbox \
		; \
	docker-php-ext-enable \
		luasandbox \
		; \
	rm -rf /var/lib/apt/lists/*

RUN set -eux; \
	apt-get update; \
	apt-get install -y --no-install-recommends \
		git \
		git-review \
		librsvg2-bin \
		imagemagick \
		# Required for SyntaxHighlighting
		python3 \
		; \
	rm -rf /var/lib/apt/lists/*

# Install the PHP extensions we need
RUN set -eux; \
	\
	savedAptMark="$(apt-mark showmanual)"; \
	\
	apt-get update; \
	apt-get install -y --no-install-recommends \
		libicu-dev \
		zlib1g-dev \
		libzip-dev \
	; \
	\
	docker-php-ext-install -j "$(nproc)" \
		intl \
		mbstring \
		mysqli \
		opcache \
		pcntl \
		zip \
		xml \
		json \
	; \
	\
	pecl install apcu-5.1.18; \
	docker-php-ext-enable \
		apcu \
	; \
	\
	# reset apt-mark's "manual" list so that "purge --auto-remove" will remove all build dependencies
	apt-mark auto '.*' > /dev/null; \
	apt-mark manual $savedAptMark; \
	ldd "$(php -r 'echo ini_get("extension_dir");')"/*.so \
		| awk '/=>/ { print $3 }' \
		| sort -u \
		| xargs -r dpkg-query -S \
		| cut -d: -f1 \
		| sort -u \
		| xargs -rt apt-mark manual; \
	\
	apt-get purge -y --auto-remove -o APT::AutoRemove::RecommendsImportant=false; \
	rm -rf /var/lib/apt/lists/*

# set recommended PHP.ini settings
# see https://secure.php.net/manual/en/opcache.installation.php
RUN { \
		echo 'opcache.memory_consumption=128'; \
		echo 'opcache.interned_strings_buffer=8'; \
		echo 'opcache.max_accelerated_files=4000'; \
		echo 'opcache.revalidate_freq=60'; \
		echo 'opcache.fast_shutdown=1'; \
	} > /usr/local/etc/php/conf.d/opcache-recommended.ini

RUN set -eux; \
	cd /var/www; \
	git clone https://gerrit.wikimedia.org/r/mediawiki/core.git mediawiki; \
	cd mediawiki; \
	git submodule update --init; \
	cd skins ; \
	git clone https://gerrit.wikimedia.org/r/mediawiki/skins/Vector.git; \
	cd /var/www/mediawiki; \
	chown -R www-data:www-data extensions skins cache images

RUN set -eux; \
	cd /var/www/mediawiki; \
	composer install

WORKDIR /root/scripts

COPY files/create_wiki.sh /root/scripts
COPY files/create_wiki.php /root/scripts
COPY files/mk-favicon.sh /root/scripts

COPY files/LocalSettings_mediawiki.php /var/www/mediawiki/LocalSettings.php

RUN mkdir /var/www/wikifarm
COPY files/LocalSettings_wikifarm.php /var/www/wikifarm/LocalSettings.php
COPY files/Keys.php /var/www/wikifarm/Keys.php
RUN sed -i -e "s/%%SECRET_KEY%%/`od -N 32 -An -vx /dev/urandom | tr '\n' ' ' | sed -e 's/ //g'`/" /var/www/wikifarm/Keys.php

COPY files/index.php /var/www/html/index.php

COPY files/wikifarm.conf /etc/apache2/conf-available
RUN a2enconf wikifarm

RUN service apache2 restart
