FROM mediawiki:1.33 AS wikifarm

RUN set -eux; \
	rm /etc/apt/preferences.d/no-debian-php; \
	apt-get update; \
	apt-get install -y --no-install-recommends \
		composer \
		lua5.1 \
		lua5.1-dev \
		libxml2-dev \
		pkg-config \
		php-xml \
		php-dom \
		zip \
		unzip \
		make \
		; \
	docker-php-ext-install -j "$(nproc)" \
		dom \
		xml \
		; \
	pecl install \
		luasandbox \
		; \
	docker-php-ext-enable \
		luasandbox \
		; \
	rm -rf /var/lib/apt/lists/*

RUN a2disconf short-url

RUN mv /var/www/html /var/www/mediawiki

WORKDIR /root/scripts

COPY files/create_wiki.sh /root/scripts
COPY files/create_wiki.php /root/scripts
COPY files/mk-favicon.sh /root/scripts

COPY files/LocalSettings_mediawiki.php /var/www/mediawiki/LocalSettings.php

RUN mkdir /var/www/wikifarm
COPY files/LocalSettings_wikifarm.php /var/www/wikifarm/LocalSettings.php
COPY files/Keys.php /var/www/wikifarm/Keys.php
RUN sed -i -e "s/%%SECRET_KEY%%/`od -N 32 -An -vx /dev/urandom | tr '\n' ' ' | sed -e 's/ //g'`/" /var/www/wikifarm/Keys.php

COPY files/index.php /var/www/html/index.php

COPY files/wikifarm.conf /etc/apache2/conf-available
RUN a2enconf wikifarm

RUN service apache2 restart
